# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---
# tasks file for render

# --------------------------------------------------------------------
# Remove all files from the previous run
# --------------------------------------------------------------------
- name: Delete content & directory
  ansible.builtin.file:
    state: absent
    path: "{{ role_path }}/files/"
  delegate_to: localhost

- name: Recreate the directory
  ansible.builtin.file:
    path: "{{ role_path }}/files/"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Add gitkeep file back to the directory
  ansible.builtin.file:
    path: "{{ role_path }}/files/.gitkeep"
    state: touch
  delegate_to: localhost

- name: Role Entry Point - [cisco.nac_dc_vxlan.render]
  ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+     Calling Role - [cisco.nac_dc_vxlan.dtc.render]           +"
      - "----------------------------------------------------------------"
  # tags: "{{ nac_tags.render }}"

- name: Render NDFC Configuration
  ansible.builtin.import_tasks: ndfc_render.yml
  when: hostvars[inventory_hostname]['ansible_network_os'] == "cisco.dcnm.dcnm"
  # tags: "{{ nac_tags.render }}"

- name: Render NXOS Configuration
  ansible.builtin.import_tasks: nxos_render.yml
  when: hostvars[inventory_hostname]['ansible_network_os'] == "cisco.nxos.nxos"
  # tags: "{{ nac_tags.render }}"